org: chaly
app: chaly-prod
service: auth

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-west-3
  stage: prod

  logs:
    httpApi: true

  httpApi:
    cors: true
    payload: "2.0"
    shouldStartNameWithService: true

  environment:
    DATABASE_URL: ${ssm:/chaly/DATABASE_URL}
    ENV: PROD
    API_KEY: ${ssm:/chaly/API_KEY}
    ACCESS_TOKEN_SECRET: ${ssm:/chaly/ACCESS_TOKEN_SECRET}
    REFRESH_TOKEN_SECRET: ${ssm:/chaly/REFRESH_TOKEN_SECRET}

  vpc:
    securityGroupIds:
      - sg-052d9cdb5230101b9
    subnetIds:
      - subnet-0db66631bb0e17003
      - subnet-0f07bc0c4a7b62f79

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - ssm:GetParameter
            - ssm:GetParameters
          Resource: "*"
        - Effect: Allow
          Action:
            - lambda:InvokeFunction
          Resource:
            - arn:aws:lambda:eu-west-3:762233728636:function:public-prod-lambda

build:
  esbuild:
    bundle: true
    minify: false
    sourcemap: false
    exclude:
      - "@aws-sdk"

functions:
  lambda:
    handler: src/index.handler
    timeout: 10
    events:
      - httpApi:
          path: /{proxy+}
          method: ANY

package:
  patterns:
    - node_modules/@prisma/client/**
    - node_modules/.prisma/**
    - "!**/*.ts"
    - dist/**
